# Generated by Django 4.2.27 on 2025-12-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='notes_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='account_type',
            field=models.CharField(choices=[('school', 'School'), ('tuition', 'Tuition/Coaching')], default='school', max_length=20),
        ),
    ]
