# Generated by Django 4.2.27 on 2025-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_sections',
            field=models.ManyToManyField(blank=True, related_name='notices', to='academic.section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='academic.subject'),
        ),
    ]
