# Generated by Django 4.2.27 on 2025-12-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academic.section'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.class'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignment', to='academic.section'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_of', to='academic.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('section', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
    ]
