# Generated by Django 4.2.27 on 2026-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_subject_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_year'), name='unique_teacher_per_academic_year'),
        ),
    ]
