# Generated by Django 4.2.27 on 2025-12-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designates if this user is the owner (mostly for Tuition mode).'),
        ),
    ]
